spring:
  application:
    name: dbimport
  datasource:
    ods:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/ods
      username: root
      password: root
logging:
  file: dbimport.log