spring:
  application:
    name: dbimport
  profiles:
    active: ods
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/ods
      username: root
      password: root
    pgsql:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5432/ods
      username: root
      password: root
logging:
  file: dbimport.log