spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/secure
    username: root
    password: root
    driver-class-name: org.postgresql.Driver