version: '2'
services:
    uapp-app:
        image: uapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://uapp-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    uapp-mssql:
        extends:
            file: mssql.yml
            service: uapp-mssql
